# http://travis-ci.org/#!/strawlab/pymvg
language: python
python:
    - 2.7
    - 3.3
before_install:
    - sudo apt-get update
    - sudo apt-get install python-opencv
install:
    - pip install numpy
    - pip install matplotlib
    - pip install pyyaml
    - python setup.py install
script:
    - nosetests -w test
