# http://travis-ci.org/#!/strawlab/pymvg
language: python
python:
    - 2.7
    - 3.3
# TODO: install OpenCV?
install:
    - pip install numpy
    - pip install matplotlib
    - python setup.py install
script:
    - nosetests
