# http://travis-ci.org/#!/strawlab/pymvg
language: python
python:
    - "2.7_with_system_site_packages"
    - "3.3"
before_install:
    - sudo apt-get update
    - sudo apt-get install python-opencv
install:
    - pip install numpy
    - pip install matplotlib
    - pip install pyyaml
    - pip install coveralls # for coverage testing
    - python setup.py install
script:
    - nosetests  --with-doctest --with-coverage --cover-package=pymvg --where=pymvg
    - if [[ $TRAVIS_PYTHON_VERSION == '2.'* ]]; then nosetests -w pymvg/test/external/opencv; fi
after_success:
    - coveralls
